version: "3.8"

services:
  app:
    image: sprc-weather-app:latest
    build: .
    container_name: app
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=${LOGGING_LEVEL_APP:-INFO}
      - LOGGING_LEVEL_ORG_HIBERNATE=${LOGGING_LEVEL_DB:-INFO}

  db:
    image: postgres:13.1
    ports:
      - "${DB_PORT:-5432}:5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres